vSphereHA:
  properties:
    - name: "vCommunity|Cluster Configuration|vSphere HA|Host Monitoring"
      configPath: "configuration.dasConfig.hostMonitoring"
    - name: "vCommunity|Cluster Configuration|vSphere HA|Response \\ Host Isolation"
      configPath: "configuration.dasConfig.defaultVmSettings.isolationResponse"
    - name: "vCommunity|Cluster Configuration|vSphere HA|Response \\ Default VM Restart Priority"
      configPath: "configuration.dasConfig.defaultVmSettings.restartPriority"
    - name: "vCommunity|Cluster Configuration|vSphere HA|Response \\ Datastore APD"
      configPath: "configuration.dasConfig.defaultVmSettings.vmComponentProtectionSettings.vmStorageProtectionForAPD"
    - name: "vCommunity|Cluster Configuration|vSphere HA|Response \\ Datastore PDL"
      configPath: "configuration.dasConfig.defaultVmSettings.vmComponentProtectionSettings.vmStorageProtectionForPDL"
    - name: "vCommunity|Cluster Configuration|vSphere HA|VM Monitoring"
      configPath: "configuration.dasConfig.vmMonitoring"
    - name: "vCommunity|Cluster Configuration|vSphere HA|Heartbeat Datastore"
      configPath: "configuration.dasConfig.hBDatastoreCandidatePolicy"
DRS:
  properties:
    - name: "vCommunity|Cluster Configuration|DRS|Proactive DRS"
      configPath: "configurationEx.proactiveDrsConfig.enabled"
    - name: "vCommunity|Cluster Configuration|DRS|Scale Descendants Shares"
      configPath: "configuration.drsConfig.scaleDescendantsShares"
  metrics:
    - name: "vCommunity|Cluster Configuration|DRS|DRS Score"
      configPath: "summary.drsScore"