Snapshot:
  metrics:
    - name: "vCommunity|Snapshot|Count"
Config:
  properties:
    - name: "vCommunity|Options|Latency Sensitivity"
      configPath: "config.latencySensitivity.level"
    - name: "vCommunity|Options|Nested HV Enabled"
      configPath: "config.nestedHVEnabled"
Age:
  properties:
    - name: "vCommunity|Summary|VM Age"
      configPath: "config.createDate"